In [1]:
import pandas as pd
import torch
from tqdm import tqdm
from transformers import AutoModelForCausalLM, AutoTokenizer, pipeline
from vllm import LLM, SamplingParams

# VLLM 모델 및 토크나이저 로드
BASE_MODEL = "cpm-ai/Ocelot-Ko-self-instruction-10.8B-v1.0"
llm = LLM(model=BASE_MODEL, max_model_len=4096,tensor_parallel_size=8,gpu_memory_utilization=0.2)

# instruction 컬럼을 순차적으로 가져와서 모델로 답변 생성 후 rejected 컬럼에 추가
output = []

/home/ubuntu/miniforge3/envs/jinsu/lib/python3.10/site-packages/huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
2024-07-29 10:17:00,775	INFO worker.py:1770 -- Started a local Ray instance.

INFO 07-29 10:17:01 config.py:623] Defaulting to use mp for distributed inference
INFO 07-29 10:17:01 llm_engine.py:161] Initializing an LLM engine (v0.5.0.post1) with config: model='cpm-ai/Ocelot-Ko-self-instruction-10.8B-v1.0', speculative_config=None, tokenizer='cpm-ai/Ocelot-Ko-self-instruction-10.8B-v1.0', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, rope_scaling=None, rope_theta=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.bfloat16, max_seq_len=4096, download_dir=None, load_format=LoadFormat.AUTO, tensor_parallel_size=8, disable_custom_all_reduce=False, quantization=None, enforce_eager=False, kv_cache_dtype=auto, quantization_param_path=None, device_config=cuda, decoding_config=DecodingConfig(guided_decoding_backend='outlines'), seed=0, served_model_name=cpm-ai/Ocelot-Ko-self-instruction-10.8B-v1.0)
(VllmWorkerProcess pid=3673852) INFO 07-29 10:17:05 multiproc_worker_utils.py:215] Worker ready; awaiting tasks
(VllmWorkerProcess pid=3673857) INFO 07-29 10:17:05 multiproc_worker_utils.py:215] Worker ready; awaiting tasks
(VllmWorkerProcess pid=3673858) INFO 07-29 10:17:05 multiproc_worker_utils.py:215] Worker ready; awaiting tasks
(VllmWorkerProcess pid=3673856) INFO 07-29 10:17:05 multiproc_worker_utils.py:215] Worker ready; awaiting tasks
(VllmWorkerProcess pid=3673855) INFO 07-29 10:17:05 multiproc_worker_utils.py:215] Worker ready; awaiting tasks
(VllmWorkerProcess pid=3673853) INFO 07-29 10:17:06 multiproc_worker_utils.py:215] Worker ready; awaiting tasks
(VllmWorkerProcess pid=3673854) INFO 07-29 10:17:06 multiproc_worker_utils.py:215] Worker ready; awaiting tasks
INFO 07-29 10:17:06 utils.py:637] Found nccl from library libnccl.so.2
(VllmWorkerProcess pid=3673852) INFO 07-29 10:17:06 utils.py:637] Found nccl from library libnccl.so.2
INFO 07-29 10:17:06 pynccl.py:63] vLLM is using nccl==2.20.5
(VllmWorkerProcess pid=3673852) INFO 07-29 10:17:06 pynccl.py:63] vLLM is using nccl==2.20.5
(VllmWorkerProcess pid=3673853) INFO 07-29 10:17:06 utils.py:637] Found nccl from library libnccl.so.2
(VllmWorkerProcess pid=3673853) INFO 07-29 10:17:06 pynccl.py:63] vLLM is using nccl==2.20.5
(VllmWorkerProcess pid=3673854) INFO 07-29 10:17:06 utils.py:637] Found nccl from library libnccl.so.2
(VllmWorkerProcess pid=3673855) INFO 07-29 10:17:06 utils.py:637] Found nccl from library libnccl.so.2
(VllmWorkerProcess pid=3673856) INFO 07-29 10:17:06 utils.py:637] Found nccl from library libnccl.so.2
(VllmWorkerProcess pid=3673854) INFO 07-29 10:17:06 pynccl.py:63] vLLM is using nccl==2.20.5
(VllmWorkerProcess pid=3673855) (VllmWorkerProcess pid=3673856) INFO 07-29 10:17:06 pynccl.py:63] vLLM is using nccl==2.20.5
INFO 07-29 10:17:06 pynccl.py:63] vLLM is using nccl==2.20.5
(VllmWorkerProcess pid=3673857) INFO 07-29 10:17:06 utils.py:637] Found nccl from library libnccl.so.2
(VllmWorkerProcess pid=3673858) INFO 07-29 10:17:06 utils.py:637] Found nccl from library libnccl.so.2
(VllmWorkerProcess pid=3673857) INFO 07-29 10:17:06 pynccl.py:63] vLLM is using nccl==2.20.5
(VllmWorkerProcess pid=3673858) INFO 07-29 10:17:06 pynccl.py:63] vLLM is using nccl==2.20.5
INFO 07-29 10:17:09 custom_all_reduce_utils.py:179] reading GPU P2P access cache from /home/ubuntu/.config/vllm/gpu_p2p_access_cache_for_0,1,2,3,4,5,6,7.json
(VllmWorkerProcess pid=3673855) (VllmWorkerProcess pid=3673853) INFO 07-29 10:17:09 custom_all_reduce_utils.py:179] reading GPU P2P access cache from /home/ubuntu/.config/vllm/gpu_p2p_access_cache_for_0,1,2,3,4,5,6,7.json
INFO 07-29 10:17:09 custom_all_reduce_utils.py:179] reading GPU P2P access cache from /home/ubuntu/.config/vllm/gpu_p2p_access_cache_for_0,1,2,3,4,5,6,7.json
(VllmWorkerProcess pid=3673856) INFO 07-29 10:17:09 custom_all_reduce_utils.py:179] reading GPU P2P access cache from /home/ubuntu/.config/vllm/gpu_p2p_access_cache_for_0,1,2,3,4,5,6,7.json

Traceback (most recent call last):
  File "/home/ubuntu/miniforge3/envs/jinsu/lib/python3.10/multiprocessing/resource_tracker.py", line 209, in main
    cache[rtype].remove(name)
KeyError: '/psm_1c799a2a'
Traceback (most recent call last):
  File "/home/ubuntu/miniforge3/envs/jinsu/lib/python3.10/multiprocessing/resource_tracker.py", line 209, in main
    cache[rtype].remove(name)
KeyError: '/psm_1c799a2a'
Traceback (most recent call last):
  File "/home/ubuntu/miniforge3/envs/jinsu/lib/python3.10/multiprocessing/resource_tracker.py", line 209, in main
    cache[rtype].remove(name)
KeyError: '/psm_1c799a2a'
Traceback (most recent call last):
  File "/home/ubuntu/miniforge3/envs/jinsu/lib/python3.10/multiprocessing/resource_tracker.py", line 209, in main
    cache[rtype].remove(name)
KeyError: '/psm_1c799a2a'
Traceback (most recent call last):
  File "/home/ubuntu/miniforge3/envs/jinsu/lib/python3.10/multiprocessing/resource_tracker.py", line 209, in main
    cache[rtype].remove(name)
KeyError: '/psm_1c799a2a'
Traceback (most recent call last):
  File "/home/ubuntu/miniforge3/envs/jinsu/lib/python3.10/multiprocessing/resource_tracker.py", line 209, in main
    cache[rtype].remove(name)
KeyError: '/psm_1c799a2a'
Traceback (most recent call last):
  File "/home/ubuntu/miniforge3/envs/jinsu/lib/python3.10/multiprocessing/resource_tracker.py", line 209, in main
    cache[rtype].remove(name)
KeyError: '/psm_1c799a2a'

(VllmWorkerProcess pid=3673852) (VllmWorkerProcess pid=3673857) (VllmWorkerProcess pid=3673858) INFO 07-29 10:17:09 custom_all_reduce_utils.py:179] reading GPU P2P access cache from /home/ubuntu/.config/vllm/gpu_p2p_access_cache_for_0,1,2,3,4,5,6,7.json
(VllmWorkerProcess pid=3673854) INFO 07-29 10:17:09 custom_all_reduce_utils.py:179] reading GPU P2P access cache from /home/ubuntu/.config/vllm/gpu_p2p_access_cache_for_0,1,2,3,4,5,6,7.json
INFO 07-29 10:17:09 custom_all_reduce_utils.py:179] reading GPU P2P access cache from /home/ubuntu/.config/vllm/gpu_p2p_access_cache_for_0,1,2,3,4,5,6,7.json
INFO 07-29 10:17:09 custom_all_reduce_utils.py:179] reading GPU P2P access cache from /home/ubuntu/.config/vllm/gpu_p2p_access_cache_for_0,1,2,3,4,5,6,7.json
INFO 07-29 10:17:10 weight_utils.py:218] Using model weights format ['*.safetensors']
(VllmWorkerProcess pid=3673855) INFO 07-29 10:17:10 weight_utils.py:218] Using model weights format ['*.safetensors']
(VllmWorkerProcess pid=3673857) INFO 07-29 10:17:10 weight_utils.py:218] Using model weights format ['*.safetensors']
(VllmWorkerProcess pid=3673853) INFO 07-29 10:17:10 weight_utils.py:218] Using model weights format ['*.safetensors']
(VllmWorkerProcess pid=3673852) INFO 07-29 10:17:10 weight_utils.py:218] Using model weights format ['*.safetensors']
(VllmWorkerProcess pid=3673856) INFO 07-29 10:17:10 weight_utils.py:218] Using model weights format ['*.safetensors']
(VllmWorkerProcess pid=3673854) INFO 07-29 10:17:10 weight_utils.py:218] Using model weights format ['*.safetensors']
(VllmWorkerProcess pid=3673858) INFO 07-29 10:17:11 weight_utils.py:218] Using model weights format ['*.safetensors']
INFO 07-29 10:17:14 model_runner.py:160] Loading model weights took 2.5173 GB
(VllmWorkerProcess pid=3673855) INFO 07-29 10:17:17 model_runner.py:160] Loading model weights took 2.5173 GB
(VllmWorkerProcess pid=3673853) INFO 07-29 10:17:19 model_runner.py:160] Loading model weights took 2.5173 GB
(VllmWorkerProcess pid=3673854) INFO 07-29 10:17:21 model_runner.py:160] Loading model weights took 2.5173 GB
(VllmWorkerProcess pid=3673857) INFO 07-29 10:17:21 model_runner.py:160] Loading model weights took 2.5173 GB
(VllmWorkerProcess pid=3673856) INFO 07-29 10:17:21 model_runner.py:160] Loading model weights took 2.5173 GB
(VllmWorkerProcess pid=3673858) INFO 07-29 10:17:21 model_runner.py:160] Loading model weights took 2.5173 GB
(VllmWorkerProcess pid=3673852) INFO 07-29 10:17:22 model_runner.py:160] Loading model weights took 2.5173 GB
INFO 07-29 10:17:26 distributed_gpu_executor.py:56] # GPU blocks: 27024, # CPU blocks: 10922
(VllmWorkerProcess pid=3673853) INFO 07-29 10:17:32 model_runner.py:889] Capturing the model for CUDA graphs. This may lead to unexpected consequences if the model is not static. To run the model in eager mode, set 'enforce_eager=True' or use '--enforce-eager' in the CLI.
(VllmWorkerProcess pid=3673853) INFO 07-29 10:17:32 model_runner.py:893] CUDA graphs can take additional 1~3 GiB memory per GPU. If you are running out of memory, consider decreasing `gpu_memory_utilization` or enforcing eager mode. You can also reduce the `max_num_seqs` as needed to decrease memory usage.
(VllmWorkerProcess pid=3673852) INFO 07-29 10:17:32 model_runner.py:889] Capturing the model for CUDA graphs. This may lead to unexpected consequences if the model is not static. To run the model in eager mode, set 'enforce_eager=True' or use '--enforce-eager' in the CLI.
(VllmWorkerProcess pid=3673852) INFO 07-29 10:17:32 model_runner.py:893] CUDA graphs can take additional 1~3 GiB memory per GPU. If you are running out of memory, consider decreasing `gpu_memory_utilization` or enforcing eager mode. You can also reduce the `max_num_seqs` as needed to decrease memory usage.
(VllmWorkerProcess pid=3673854) INFO 07-29 10:17:33 model_runner.py:889] Capturing the model for CUDA graphs. This may lead to unexpected consequences if the model is not static. To run the model in eager mode, set 'enforce_eager=True' or use '--enforce-eager' in the CLI.
(VllmWorkerProcess pid=3673854) INFO 07-29 10:17:33 model_runner.py:893] CUDA graphs can take additional 1~3 GiB memory per GPU. If you are running out of memory, consider decreasing `gpu_memory_utilization` or enforcing eager mode. You can also reduce the `max_num_seqs` as needed to decrease memory usage.
(VllmWorkerProcess pid=3673855) INFO 07-29 10:17:33 model_runner.py:889] Capturing the model for CUDA graphs. This may lead to unexpected consequences if the model is not static. To run the model in eager mode, set 'enforce_eager=True' or use '--enforce-eager' in the CLI.
(VllmWorkerProcess pid=3673855) INFO 07-29 10:17:33 model_runner.py:893] CUDA graphs can take additional 1~3 GiB memory per GPU. If you are running out of memory, consider decreasing `gpu_memory_utilization` or enforcing eager mode. You can also reduce the `max_num_seqs` as needed to decrease memory usage.
(VllmWorkerProcess pid=3673857) INFO 07-29 10:17:33 model_runner.py:889] Capturing the model for CUDA graphs. This may lead to unexpected consequences if the model is not static. To run the model in eager mode, set 'enforce_eager=True' or use '--enforce-eager' in the CLI.
(VllmWorkerProcess pid=3673857) INFO 07-29 10:17:33 model_runner.py:893] CUDA graphs can take additional 1~3 GiB memory per GPU. If you are running out of memory, consider decreasing `gpu_memory_utilization` or enforcing eager mode. You can also reduce the `max_num_seqs` as needed to decrease memory usage.
(VllmWorkerProcess pid=3673856) INFO 07-29 10:17:33 model_runner.py:889] Capturing the model for CUDA graphs. This may lead to unexpected consequences if the model is not static. To run the model in eager mode, set 'enforce_eager=True' or use '--enforce-eager' in the CLI.
(VllmWorkerProcess pid=3673856) INFO 07-29 10:17:33 model_runner.py:893] CUDA graphs can take additional 1~3 GiB memory per GPU. If you are running out of memory, consider decreasing `gpu_memory_utilization` or enforcing eager mode. You can also reduce the `max_num_seqs` as needed to decrease memory usage.
(VllmWorkerProcess pid=3673858) INFO 07-29 10:17:33 model_runner.py:889] Capturing the model for CUDA graphs. This may lead to unexpected consequences if the model is not static. To run the model in eager mode, set 'enforce_eager=True' or use '--enforce-eager' in the CLI.
(VllmWorkerProcess pid=3673858) INFO 07-29 10:17:33 model_runner.py:893] CUDA graphs can take additional 1~3 GiB memory per GPU. If you are running out of memory, consider decreasing `gpu_memory_utilization` or enforcing eager mode. You can also reduce the `max_num_seqs` as needed to decrease memory usage.
INFO 07-29 10:17:33 model_runner.py:889] Capturing the model for CUDA graphs. This may lead to unexpected consequences if the model is not static. To run the model in eager mode, set 'enforce_eager=True' or use '--enforce-eager' in the CLI.
INFO 07-29 10:17:33 model_runner.py:893] CUDA graphs can take additional 1~3 GiB memory per GPU. If you are running out of memory, consider decreasing `gpu_memory_utilization` or enforcing eager mode. You can also reduce the `max_num_seqs` as needed to decrease memory usage.
INFO 07-29 10:17:55 custom_all_reduce.py:267] Registering 3395 cuda graph addresses
(VllmWorkerProcess pid=3673854) INFO 07-29 10:17:55 custom_all_reduce.py:267] Registering 3395 cuda graph addresses
(VllmWorkerProcess pid=3673852) INFO 07-29 10:17:55 custom_all_reduce.py:267] Registering 3395 cuda graph addresses
(VllmWorkerProcess pid=3673856) INFO 07-29 10:17:55 custom_all_reduce.py:267] Registering 3395 cuda graph addresses
(VllmWorkerProcess pid=3673855) INFO 07-29 10:17:55 custom_all_reduce.py:267] Registering 3395 cuda graph addresses
(VllmWorkerProcess pid=3673853) (VllmWorkerProcess pid=3673858) INFO 07-29 10:17:55 custom_all_reduce.py:267] Registering 3395 cuda graph addresses
INFO 07-29 10:17:55 custom_all_reduce.py:267] Registering 3395 cuda graph addresses
(VllmWorkerProcess pid=3673857) INFO 07-29 10:17:55 custom_all_reduce.py:267] Registering 3395 cuda graph addresses
(VllmWorkerProcess pid=3673856) INFO 07-29 10:17:55 model_runner.py:965] Graph capturing finished in 22 secs.
(VllmWorkerProcess pid=3673855) INFO 07-29 10:17:55 model_runner.py:965] Graph capturing finished in 22 secs.
(VllmWorkerProcess pid=3673854) INFO 07-29 10:17:55 model_runner.py:965] Graph capturing finished in 22 secs.
INFO 07-29 10:17:55 model_runner.py:965] Graph capturing finished in 22 secs.
(VllmWorkerProcess pid=3673857) INFO 07-29 10:17:55 model_runner.py:965] Graph capturing finished in 22 secs.
(VllmWorkerProcess pid=3673852) INFO 07-29 10:17:55 model_runner.py:965] Graph capturing finished in 22 secs.
(VllmWorkerProcess pid=3673858) INFO 07-29 10:17:55 model_runner.py:965] Graph capturing finished in 22 secs.
(VllmWorkerProcess pid=3673853) INFO 07-29 10:17:55 model_runner.py:965] Graph capturing finished in 22 secs.

In [61]:
# CSV 파일 불러오기
import pandas as pd
df = pd.read_csv('./data/추론2000_final.csv')
df

                                            instruction  option
0     [Conversation]\n화자1: 국민지원금 신청 일이 다가오네요\n화자2: 아...     NaN
1     [Conversation]\n화자1: 국민지원금 신청 일이 다가오네요\n화자2: 아...     NaN
2     [Conversation]\n화자1: 국민지원금 신청 일이 다가오네요\n화자2: 아...     NaN
3     [Conversation]\n화자1: 국민지원금 신청 일이 다가오네요\n화자2: 아...     NaN
4     [Conversation]\n화자1: 국민지원금 신청 일이 다가오네요\n화자2: 아...     NaN
...                                                 ...     ...
1995  [Conversation]\n화자1: 기숙사 생활하신 경험이 있으신가요?\n화자2:...     NaN
1996  [Conversation]\n화자1: 기숙사 생활하신 경험이 있으신가요?\n화자2:...     NaN
1997  [Conversation]\n화자1: 기숙사 생활하신 경험이 있으신가요?\n화자2:...     NaN
1998  [Conversation]\n화자1: 기숙사 생활하신 경험이 있으신가요?\n화자2:...     NaN
1999  [Conversation]\n화자1: 기숙사 생활하신 경험이 있으신가요?\n화자2:...     NaN

[2000 rows x 2 columns]

In [62]:
system_prompt = """
당신의 목표는 일상대화[Conversation]와 문제[Question], 답변[Answer]을 보고 옵션값을 생성하는것입니다. 답변은 한국어로 출력합니다.

출력은 다음 지침을 준수하십시오:
1. 먼저 두 화자가 무슨 주제를 가지고 대화 중인지 파악한 후에
2. 주제와 관련된 3가지 옵션을 출력해주세요. 옵션에는 꼭 [Answer]이  포함되어야 하며 A, B, C 옵션으로 출력합니다.
3. 3가지 옵션 중 정답은 랜덤으로 들어가며 정답은 항상 생성된 옵션 중 하나입니다.
4. 각 옵션은 명확히 구분되고, 가능한 한 다양한 방식으로 표현되도록 합니다.

예시입니다.

[Conversation]
화자2: 흠ㅋㅋㅋ 어쨌든 이제 카페 자주 들어가서 ... 쫓겨나지 않게 잘 버텨봐야죠
화자1: ㅋㅋㅋㅋㅋㅋㅋ 아 맞다 저 인증하는거 까먹고 있었는데
화자1: 지금 해야겠네요..
화자2: 그거 까딱하면 까먹어버려요 빨리 빨리 해 버려야 해요 ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ
화자1: 맞아요.. 입금으로 대충 때우고
화자2: 카페는 보통 어떻게 활용하고 계신가요? 주변에 거기 가입한 다른 분이 없어서 궁금해요
화자1: 저는 그냥 정보만 확인하는 정도에요! 아니면 제가 정보글을 올리거나요
화자2: 앗 저도 거의 확인용... 좋은 정보 공유하는 멋진 회원이 되고 싶은데
화자2: 현실은 줍줍 인간이네요
화자1: ㅋㅋㅋㅋㅋㅋ 근데 올릴 게 딱히 없어요..
화자1: 주식하는 사람도 많다던데 전 주식을 안 해서
화자2: 그럼 어떤 정보 주로 확인하시나요??
화자1: 저 그냥 이것저것 올라오는 거요 ㅋㅋㅋㅋ 이런 앱테크도 확인하고..
화자2: 아하ㅋㅋㅋㅋㅋㅋ 저는 주식 공부 시작한 지 이제 딱 일 년 좀 넘어가요
화자1: 주식 공부 저는 미루는 중이에요 현생이 너무 바빠서 ㅜㅜ
화자2: 아하 현생... 공부할 것이 많으시지요 참ㅠㅠㅠ
화자2: 저도 얄팍하게만 공부해두고 망할 것 같지 않은 주식에만... 적금처럼 넣고 있어요
화자1: 망할 것 같지 않은ㅋㅋㅋㅋ

[Question] 다음 중 (원인)에 해당하는 것은 무엇인가요?

[Answer] 화자2는 주식을 잘 알지 못한다.

[Option]
A. 화자1은 조심스럽게 주식 투자를 하는 화자2가 귀엽다고 생각한다.
B. 화자2는 주식을 잘 알지 못한다.
C. 화자2는 주식 공부를 시작한 지 이제 딱 일 년 좀 넘었다.

[정답] 
B

위와 같이 Option을 생성해주세요
"""

In [67]:
# 샘플링 파라미터 설정
sampling_params = SamplingParams(temperature=0, max_tokens=1024)

for instruction in tqdm(df['instruction']):
    
    # 템플릿에 instruction 삽입
    text = system_prompt + instruction
    
    # 답변 생성
    outputs = llm.generate([text], sampling_params)
    
    # 생성된 텍스트 추출
    response = outputs[0].outputs[0].text.strip()
    
    # rejected_responses 리스트에 답변 추가
    output.append(response)

# 새로운 rejected 컬럼 추가
df['option'] = output

Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.79it/s, est. speed input: 1779.67 toks/s, output: 107.64 toks/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.65it/s, est. speed input: 1653.41 toks/s, output: 114.54 toks/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.90it/s, est. speed input: 1887.22 toks/s, output: 114.49 toks/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.49it/s, est. speed input: 1498.33 toks/s, output: 115.25 toks/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.52it/s, est. speed input: 1527.42 toks/s, output: 116.20 toks/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.63it/s, est. speed input: 1825.64 toks/s, output: 114.51 toks/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.50it/s, est. speed input: 1696.67 toks/s, output: 114.41 toks/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.55it/s, est. speed input: 1737.82 toks/s, output: 111.91 toks/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.55it/s, est. speed input: 1743.99 toks/s, output: 113.36 toks/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.59it/s, est. speed input: 1796.26 toks/s, output: 114.75 toks/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.82it/s, est. speed input: 1778.44 toks/s, output: 113.32 toks/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.78it/s, est. speed input: 1741.34 toks/s, output: 114.30 toks/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.50it/s, est. speed input: 1474.17 toks/s, output: 116.06 toks/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.87it/s, est. speed input: 1831.44 toks/s, output: 114.69 toks/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.68it/s, est. speed input: 1648.65 toks/s, output: 114.98 toks/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.70it/s, est. speed input: 2014.89 toks/s, output: 112.60 toks/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.59it/s, est. speed input: 1895.53 toks/s, output: 111.87 toks/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.45it/s, est. speed input: 1726.36 toks/s, output: 113.53 toks/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.56it/s, est. speed input: 1858.05 toks/s, output: 114.07 toks/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.32it/s, est. speed input: 1579.93 toks/s, output: 114.27 toks/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.87it/s, est. speed input: 2108.83 toks/s, output: 111.08 toks/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.42it/s, est. speed input: 1608.71 toks/s, output: 115.21 toks/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  2.09it/s, est. speed input: 2357.48 toks/s, output: 109.25 toks/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.53it/s, est. speed input: 1732.44 toks/s, output: 113.25 toks/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.23it/s, est. speed input: 1394.49 toks/s, output: 116.20 toks/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.86it/s, est. speed input: 1764.30 toks/s, output: 114.12 toks/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.89it/s, est. speed input: 1795.56 toks/s, output: 113.76 toks/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  2.29it/s, est. speed input: 2162.68 toks/s, output: 112.61 toks/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.83it/s, est. speed input: 1735.77 toks/s, output: 110.32 toks/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.55it/s, est. speed input: 1479.82 toks/s, output: 116.45 toks/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.31it/s, est. speed input: 1404.38 toks/s, output: 114.08 toks/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.24it/s, est. speed input: 1331.32 toks/s, output: 111.98 toks/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.58it/s, est. speed input: 1689.64 toks/s, output: 114.12 toks/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.31it/s, est. speed input: 1408.75 toks/s, output: 115.86 toks/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.40it/s, est. speed input: 1498.34 toks/s, output: 114.17 toks/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.45it/s, est. speed input: 1287.30 toks/s, output: 115.17 toks/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.48it/s, est. speed input: 1317.61 toks/s, output: 114.63 toks/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.70it/s, est. speed input: 1505.09 toks/s, output: 114.33 toks/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.72it/s, est. speed input: 1527.02 toks/s, output: 115.99 toks/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.64it/s, est. speed input: 1452.87 toks/s, output: 116.81 toks/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.25it/s, est. speed input: 1208.36 toks/s, output: 117.58 toks/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.81it/s, est. speed input: 1747.52 toks/s, output: 114.19 toks/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.57it/s, est. speed input: 1508.32 toks/s, output: 116.26 toks/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.36it/s, est. speed input: 1308.16 toks/s, output: 114.34 toks/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.41it/s, est. speed input: 1363.17 toks/s, output: 116.43 toks/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.97it/s, est. speed input: 1895.48 toks/s, output: 113.01 toks/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.67it/s, est. speed input: 1607.97 toks/s, output: 114.37 toks/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  2.01it/s, est. speed input: 1934.33 toks/s, output: 115.33 toks/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.56it/s, est. speed input: 1503.40 toks/s, output: 114.32 toks/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.53it/s, est. speed input: 1470.52 toks/s, output: 114.88 toks/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.53it/s, est. speed input: 1769.92 toks/s, output: 113.49 toks/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.42it/s, est. speed input: 1651.77 toks/s, output: 114.30 toks/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.93it/s, est. speed input: 2223.39 toks/s, output: 112.32 toks/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.71it/s, est. speed input: 1983.16 toks/s, output: 111.89 toks/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.51it/s, est. speed input: 1753.52 toks/s, output: 113.96 toks/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.56it/s, est. speed input: 1725.71 toks/s, output: 114.31 toks/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.57it/s, est. speed input: 1755.34 toks/s, output: 115.33 toks/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.53it/s, est. speed input: 1705.29 toks/s, output: 115.22 toks/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.39it/s, est. speed input: 1545.91 toks/s, output: 116.77 toks/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.55it/s, est. speed input: 1739.23 toks/s, output: 113.76 toks/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.90it/s, est. speed input: 1988.70 toks/s, output: 112.60 toks/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.35it/s, est. speed input: 1420.51 toks/s, output: 117.69 toks/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.94it/s, est. speed input: 2033.10 toks/s, output: 113.05 toks/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.59it/s, est. speed input: 1671.69 toks/s, output: 114.84 toks/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.75it/s, est. speed input: 1837.85 toks/s, output: 113.98 toks/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.45it/s, est. speed input: 1613.03 toks/s, output: 113.45 toks/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.67it/s, est. speed input: 1864.54 toks/s, output: 110.76 toks/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.96it/s, est. speed input: 2187.03 toks/s, output: 110.43 toks/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.69it/s, est. speed input: 1877.32 toks/s, output: 115.11 toks/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.56it/s, est. speed input: 1735.56 toks/s, output: 115.60 toks/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.71it/s, est. speed input: 1833.28 toks/s, output: 115.11 toks/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.51it/s, est. speed input: 1628.07 toks/s, output: 115.42 toks/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.51it/s, est. speed input: 1621.46 toks/s, output: 115.06 toks/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.45it/s, est. speed input: 1559.13 toks/s, output: 116.02 toks/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.72it/s, est. speed input: 1847.05 toks/s, output: 114.03 toks/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.12it/s, est. speed input: 1438.52 toks/s, output: 116.88 toks/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.66it/s, est. speed input: 2130.34 toks/s, output: 113.52 toks/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.71it/s, est. speed input: 2188.38 toks/s, output: 114.81 toks/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.42it/s, est. speed input: 1822.91 toks/s, output: 113.84 toks/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.68it/s, est. speed input: 2149.85 toks/s, output: 112.88 toks/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.71it/s, est. speed input: 1790.28 toks/s, output: 114.89 toks/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.45it/s, est. speed input: 1520.61 toks/s, output: 116.07 toks/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.96it/s, est. speed input: 2053.60 toks/s, output: 114.19 toks/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.57it/s, est. speed input: 1647.46 toks/s, output: 113.50 toks/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.80it/s, est. speed input: 1887.65 toks/s, output: 111.77 toks/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.81it/s, est. speed input: 1655.42 toks/s, output: 114.60 toks/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.54it/s, est. speed input: 1410.03 toks/s, output: 114.15 toks/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  2.07it/s, est. speed input: 1887.88 toks/s, output: 114.10 toks/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.63it/s, est. speed input: 1493.52 toks/s, output: 116.01 toks/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.73it/s, est. speed input: 1584.37 toks/s, output: 114.53 toks/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  2.01it/s, est. speed input: 2125.62 toks/s, output: 112.82 toks/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.75it/s, est. speed input: 1861.40 toks/s, output: 112.17 toks/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  2.17it/s, est. speed input: 2304.95 toks/s, output: 113.17 toks/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.67it/s, est. speed input: 1772.75 toks/s, output: 115.17 toks/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.78it/s, est. speed input: 1893.06 toks/s, output: 115.97 toks/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.84it/s, est. speed input: 1553.37 toks/s, output: 116.36 toks/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.62it/s, est. speed input: 1383.26 toks/s, output: 117.30 toks/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.61it/s, est. speed input: 1370.00 toks/s, output: 117.65 toks/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.62it/s, est. speed input: 1373.10 toks/s, output: 116.58 toks/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.36it/s, est. speed input: 1157.69 toks/s, output: 116.99 toks/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.67it/s, est. speed input: 1786.22 toks/s, output: 113.94 toks/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.46it/s, est. speed input: 1571.19 toks/s, output: 114.64 toks/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  2.28it/s, est. speed input: 2439.34 toks/s, output: 112.65 toks/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.56it/s, est. speed input: 1674.67 toks/s, output: 114.25 toks/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.56it/s, est. speed input: 1672.55 toks/s, output: 115.67 toks/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.65it/s, est. speed input: 1586.89 toks/s, output: 116.07 toks/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.58it/s, est. speed input: 1522.68 toks/s, output: 115.78 toks/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.74it/s, est. speed input: 1663.04 toks/s, output: 115.17 toks/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.45it/s, est. speed input: 1395.76 toks/s, output: 116.31 toks/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.66it/s, est. speed input: 1593.61 toks/s, output: 115.02 toks/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.47it/s, est. speed input: 1607.69 toks/s, output: 115.15 toks/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.33it/s, est. speed input: 1458.55 toks/s, output: 115.78 toks/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.47it/s, est. speed input: 1614.62 toks/s, output: 113.95 toks/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.55it/s, est. speed input: 1691.82 toks/s, output: 114.96 toks/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.39it/s, est. speed input: 1519.28 toks/s, output: 112.90 toks/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.62it/s, est. speed input: 1528.98 toks/s, output: 113.61 toks/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.48it/s, est. speed input: 1406.81 toks/s, output: 115.99 toks/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.69it/s, est. speed input: 1593.48 toks/s, output: 115.27 toks/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.66it/s, est. speed input: 1582.92 toks/s, output: 113.66 toks/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.68it/s, est. speed input: 1588.91 toks/s, output: 116.13 toks/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.72it/s, est. speed input: 1514.89 toks/s, output: 115.47 toks/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.65it/s, est. speed input: 1460.46 toks/s, output: 116.04 toks/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.52it/s, est. speed input: 1342.37 toks/s, output: 117.32 toks/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.39it/s, est. speed input: 1223.45 toks/s, output: 118.17 toks/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.67it/s, est. speed input: 1482.95 toks/s, output: 117.56 toks/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.70it/s, est. speed input: 1989.52 toks/s, output: 114.12 toks/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.45it/s, est. speed input: 1714.06 toks/s, output: 113.78 toks/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.78it/s, est. speed input: 2086.82 toks/s, output: 114.24 toks/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.65it/s, est. speed input: 1938.75 toks/s, output: 114.33 toks/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.41it/s, est. speed input: 1655.01 toks/s, output: 114.87 toks/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.59it/s, est. speed input: 1733.12 toks/s, output: 115.11 toks/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.42it/s, est. speed input: 1539.68 toks/s, output: 115.05 toks/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.82it/s, est. speed input: 1985.03 toks/s, output: 111.49 toks/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.36it/s, est. speed input: 1497.48 toks/s, output: 115.92 toks/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.63it/s, est. speed input: 1772.48 toks/s, output: 114.35 toks/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.33it/s, est. speed input: 1355.14 toks/s, output: 116.38 toks/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.63it/s, est. speed input: 1655.76 toks/s, output: 115.93 toks/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  2.09it/s, est. speed input: 2116.15 toks/s, output: 113.14 toks/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.71it/s, est. speed input: 1741.01 toks/s, output: 114.69 toks/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.54it/s, est. speed input: 1575.52 toks/s, output: 116.18 toks/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.55it/s, est. speed input: 2137.04 toks/s, output: 115.01 toks/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.67it/s, est. speed input: 2304.87 toks/s, output: 112.06 toks/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  2.04it/s, est. speed input: 2825.24 toks/s, output: 110.79 toks/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.63it/s, est. speed input: 2255.69 toks/s, output: 112.78 toks/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.69it/s, est. speed input: 2334.66 toks/s, output: 113.51 toks/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.80it/s, est. speed input: 1996.57 toks/s, output: 113.93 toks/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.36it/s, est. speed input: 1515.29 toks/s, output: 114.56 toks/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.78it/s, est. speed input: 1983.81 toks/s, output: 112.49 toks/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.78it/s, est. speed input: 1988.84 toks/s, output: 114.56 toks/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.29it/s, est. speed input: 1440.93 toks/s, output: 115.01 toks/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.54it/s, est. speed input: 1472.66 toks/s, output: 114.23 toks/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.79it/s, est. speed input: 1709.80 toks/s, output: 114.70 toks/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.46it/s, est. speed input: 1397.38 toks/s, output: 115.35 toks/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.51it/s, est. speed input: 1452.63 toks/s, output: 115.23 toks/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.59it/s, est. speed input: 1527.68 toks/s, output: 116.77 toks/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.80it/s, est. speed input: 1851.34 toks/s, output: 113.78 toks/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.73it/s, est. speed input: 1771.45 toks/s, output: 116.01 toks/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.90it/s, est. speed input: 1960.65 toks/s, output: 112.74 toks/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.40it/s, est. speed input: 1444.57 toks/s, output: 115.56 toks/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.27it/s, est. speed input: 1311.93 toks/s, output: 115.57 toks/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  2.46it/s, est. speed input: 2201.86 toks/s, output: 113.80 toks/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.43it/s, est. speed input: 1293.95 toks/s, output: 115.81 toks/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.75it/s, est. speed input: 1572.77 toks/s, output: 115.85 toks/s]

(VllmWorkerProcess pid=3673852) ERROR 07-29 12:03:23 multiproc_worker_utils.py:226] Exception in worker VllmWorkerProcess while processing method start_worker_execution_loop: [../third_party/gloo/gloo/transport/tcp/unbound_buffer.cc:81] Timed out waiting 1800000ms for recv operation to complete, Traceback (most recent call last):
(VllmWorkerProcess pid=3673852) ERROR 07-29 12:03:23 multiproc_worker_utils.py:226]   File "/home/ubuntu/miniforge3/envs/jinsu/lib/python3.10/site-packages/vllm/executor/multiproc_worker_utils.py", line 223, in _run_worker_process
(VllmWorkerProcess pid=3673852) ERROR 07-29 12:03:23 multiproc_worker_utils.py:226]     output = executor(*args, **kwargs)
(VllmWorkerProcess pid=3673852) ERROR 07-29 12:03:23 multiproc_worker_utils.py:226]   File "/home/ubuntu/miniforge3/envs/jinsu/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
(VllmWorkerProcess pid=3673852) ERROR 07-29 12:03:23 multiproc_worker_utils.py:226]     return func(*args, **kwargs)
(VllmWorkerProcess pid=3673852) ERROR 07-29 12:03:23 multiproc_worker_utils.py:226]   File "/home/ubuntu/miniforge3/envs/jinsu/lib/python3.10/site-packages/vllm/worker/worker.py", line 294, in start_worker_execution_loop
(VllmWorkerProcess pid=3673852) ERROR 07-29 12:03:23 multiproc_worker_utils.py:226]     while self._execute_model_non_driver():
(VllmWorkerProcess pid=3673852) ERROR 07-29 12:03:23 multiproc_worker_utils.py:226]   File "/home/ubuntu/miniforge3/envs/jinsu/lib/python3.10/site-packages/vllm/worker/worker.py", line 303, in _execute_model_non_driver
(VllmWorkerProcess pid=3673852) ERROR 07-29 12:03:23 multiproc_worker_utils.py:226]     data = broadcast_tensor_dict(src=0)
(VllmWorkerProcess pid=3673852) ERROR 07-29 12:03:23 multiproc_worker_utils.py:226]   File "/home/ubuntu/miniforge3/envs/jinsu/lib/python3.10/site-packages/vllm/distributed/communication_op.py", line 32, in broadcast_tensor_dict
(VllmWorkerProcess pid=3673852) ERROR 07-29 12:03:23 multiproc_worker_utils.py:226]     return get_tp_group().broadcast_tensor_dict(tensor_dict, src)
(VllmWorkerProcess pid=3673852) ERROR 07-29 12:03:23 multiproc_worker_utils.py:226]   File "/home/ubuntu/miniforge3/envs/jinsu/lib/python3.10/site-packages/vllm/distributed/parallel_state.py", line 399, in broadcast_tensor_dict
(VllmWorkerProcess pid=3673852) ERROR 07-29 12:03:23 multiproc_worker_utils.py:226]     torch.distributed.broadcast_object_list(recv_metadata_list,
(VllmWorkerProcess pid=3673852) ERROR 07-29 12:03:23 multiproc_worker_utils.py:226]   File "/home/ubuntu/miniforge3/envs/jinsu/lib/python3.10/site-packages/torch/distributed/c10d_logger.py", line 75, in wrapper
(VllmWorkerProcess pid=3673852) ERROR 07-29 12:03:23 multiproc_worker_utils.py:226]     return func(*args, **kwargs)
(VllmWorkerProcess pid=3673852) ERROR 07-29 12:03:23 multiproc_worker_utils.py:226]   File "/home/ubuntu/miniforge3/envs/jinsu/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 2649, in broadcast_object_list
(VllmWorkerProcess pid=3673852) ERROR 07-29 12:03:23 multiproc_worker_utils.py:226]     broadcast(object_sizes_tensor, src=src, group=group)
(VllmWorkerProcess pid=3673852) ERROR 07-29 12:03:23 multiproc_worker_utils.py:226]   File "/home/ubuntu/miniforge3/envs/jinsu/lib/python3.10/site-packages/torch/distributed/c10d_logger.py", line 75, in wrapper
(VllmWorkerProcess pid=3673852) ERROR 07-29 12:03:23 multiproc_worker_utils.py:226]     return func(*args, **kwargs)
(VllmWorkerProcess pid=3673852) ERROR 07-29 12:03:23 multiproc_worker_utils.py:226]   File "/home/ubuntu/miniforge3/envs/jinsu/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 2144, in broadcast
(VllmWorkerProcess pid=3673852) ERROR 07-29 12:03:23 multiproc_worker_utils.py:226]     work.wait()
(VllmWorkerProcess pid=3673852) ERROR 07-29 12:03:23 multiproc_worker_utils.py:226] RuntimeError: [../third_party/gloo/gloo/transport/tcp/unbound_buffer.cc:81] Timed out waiting 1800000ms for recv operation to complete
(VllmWorkerProcess pid=3673852) ERROR 07-29 12:03:23 multiproc_worker_utils.py:226]
(VllmWorkerProcess pid=3673854) ERROR 07-29 12:03:23 multiproc_worker_utils.py:226] Exception in worker VllmWorkerProcess while processing method start_worker_execution_loop: [../third_party/gloo/gloo/transport/tcp/unbound_buffer.cc:81] Timed out waiting 1800000ms for recv operation to complete, Traceback (most recent call last):
(VllmWorkerProcess pid=3673854) ERROR 07-29 12:03:23 multiproc_worker_utils.py:226]   File "/home/ubuntu/miniforge3/envs/jinsu/lib/python3.10/site-packages/vllm/executor/multiproc_worker_utils.py", line 223, in _run_worker_process
(VllmWorkerProcess pid=3673854) ERROR 07-29 12:03:23 multiproc_worker_utils.py:226]     output = executor(*args, **kwargs)
(VllmWorkerProcess pid=3673854) ERROR 07-29 12:03:23 multiproc_worker_utils.py:226]   File "/home/ubuntu/miniforge3/envs/jinsu/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
(VllmWorkerProcess pid=3673854) ERROR 07-29 12:03:23 multiproc_worker_utils.py:226]     return func(*args, **kwargs)
(VllmWorkerProcess pid=3673854) ERROR 07-29 12:03:23 multiproc_worker_utils.py:226]   File "/home/ubuntu/miniforge3/envs/jinsu/lib/python3.10/site-packages/vllm/worker/worker.py", line 294, in start_worker_execution_loop
(VllmWorkerProcess pid=3673854) ERROR 07-29 12:03:23 multiproc_worker_utils.py:226]     while self._execute_model_non_driver():
(VllmWorkerProcess pid=3673854) ERROR 07-29 12:03:23 multiproc_worker_utils.py:226]   File "/home/ubuntu/miniforge3/envs/jinsu/lib/python3.10/site-packages/vllm/worker/worker.py", line 303, in _execute_model_non_driver
(VllmWorkerProcess pid=3673854) ERROR 07-29 12:03:23 multiproc_worker_utils.py:226]     data = broadcast_tensor_dict(src=0)
(VllmWorkerProcess pid=3673854) ERROR 07-29 12:03:23 multiproc_worker_utils.py:226]   File "/home/ubuntu/miniforge3/envs/jinsu/lib/python3.10/site-packages/vllm/distributed/communication_op.py", line 32, in broadcast_tensor_dict
(VllmWorkerProcess pid=3673854) ERROR 07-29 12:03:23 multiproc_worker_utils.py:226]     return get_tp_group().broadcast_tensor_dict(tensor_dict, src)
(VllmWorkerProcess pid=3673854) ERROR 07-29 12:03:23 multiproc_worker_utils.py:226]   File "/home/ubuntu/miniforge3/envs/jinsu/lib/python3.10/site-packages/vllm/distributed/parallel_state.py", line 399, in broadcast_tensor_dict
(VllmWorkerProcess pid=3673854) ERROR 07-29 12:03:23 multiproc_worker_utils.py:226]     torch.distributed.broadcast_object_list(recv_metadata_list,
(VllmWorkerProcess pid=3673854) ERROR 07-29 12:03:23 multiproc_worker_utils.py:226]   File "/home/ubuntu/miniforge3/envs/jinsu/lib/python3.10/site-packages/torch/distributed/c10d_logger.py", line 75, in wrapper
(VllmWorkerProcess pid=3673854) ERROR 07-29 12:03:23 multiproc_worker_utils.py:226]     return func(*args, **kwargs)
(VllmWorkerProcess pid=3673854) ERROR 07-29 12:03:23 multiproc_worker_utils.py:226]   File "/home/ubuntu/miniforge3/envs/jinsu/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 2649, in broadcast_object_list
(VllmWorkerProcess pid=3673854) ERROR 07-29 12:03:23 multiproc_worker_utils.py:226]     broadcast(object_sizes_tensor, src=src, group=group)
(VllmWorkerProcess pid=3673854) ERROR 07-29 12:03:23 multiproc_worker_utils.py:226]   File "/home/ubuntu/miniforge3/envs/jinsu/lib/python3.10/site-packages/torch/distributed/c10d_logger.py", line 75, in wrapper
(VllmWorkerProcess pid=3673854) ERROR 07-29 12:03:23 multiproc_worker_utils.py:226]     return func(*args, **kwargs)
(VllmWorkerProcess pid=3673854) ERROR 07-29 12:03:23 multiproc_worker_utils.py:226]   File "/home/ubuntu/miniforge3/envs/jinsu/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 2144, in broadcast
(VllmWorkerProcess pid=3673854) ERROR 07-29 12:03:23 multiproc_worker_utils.py:226]     work.wait()
(VllmWorkerProcess pid=3673854) ERROR 07-29 12:03:23 multiproc_worker_utils.py:226] RuntimeError: [../third_party/gloo/gloo/transport/tcp/unbound_buffer.cc:81] Timed out waiting 1800000ms for recv operation to complete
(VllmWorkerProcess pid=3673854) ERROR 07-29 12:03:23 multiproc_worker_utils.py:226]
(VllmWorkerProcess pid=3673853) ERROR 07-29 12:03:23 multiproc_worker_utils.py:226] Exception in worker VllmWorkerProcess while processing method start_worker_execution_loop: [../third_party/gloo/gloo/transport/tcp/unbound_buffer.cc:81] Timed out waiting 1800000ms for recv operation to complete, Traceback (most recent call last):
(VllmWorkerProcess pid=3673853) ERROR 07-29 12:03:23 multiproc_worker_utils.py:226]   File "/home/ubuntu/miniforge3/envs/jinsu/lib/python3.10/site-packages/vllm/executor/multiproc_worker_utils.py", line 223, in _run_worker_process
(VllmWorkerProcess pid=3673853) ERROR 07-29 12:03:23 multiproc_worker_utils.py:226]     output = executor(*args, **kwargs)
(VllmWorkerProcess pid=3673853) ERROR 07-29 12:03:23 multiproc_worker_utils.py:226]   File "/home/ubuntu/miniforge3/envs/jinsu/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
(VllmWorkerProcess pid=3673853) ERROR 07-29 12:03:23 multiproc_worker_utils.py:226]     return func(*args, **kwargs)
(VllmWorkerProcess pid=3673853) ERROR 07-29 12:03:23 multiproc_worker_utils.py:226]   File "/home/ubuntu/miniforge3/envs/jinsu/lib/python3.10/site-packages/vllm/worker/worker.py", line 294, in start_worker_execution_loop
(VllmWorkerProcess pid=3673853) ERROR 07-29 12:03:23 multiproc_worker_utils.py:226]     while self._execute_model_non_driver():
(VllmWorkerProcess pid=3673853) ERROR 07-29 12:03:23 multiproc_worker_utils.py:226]   File "/home/ubuntu/miniforge3/envs/jinsu/lib/python3.10/site-packages/vllm/worker/worker.py", line 303, in _execute_model_non_driver
(VllmWorkerProcess pid=3673853) ERROR 07-29 12:03:23 multiproc_worker_utils.py:226]     data = broadcast_tensor_dict(src=0)
(VllmWorkerProcess pid=3673853) ERROR 07-29 12:03:23 multiproc_worker_utils.py:226]   File "/home/ubuntu/miniforge3/envs/jinsu/lib/python3.10/site-packages/vllm/distributed/communication_op.py", line 32, in broadcast_tensor_dict
(VllmWorkerProcess pid=3673853) ERROR 07-29 12:03:23 multiproc_worker_utils.py:226]     return get_tp_group().broadcast_tensor_dict(tensor_dict, src)
(VllmWorkerProcess pid=3673853) ERROR 07-29 12:03:23 multiproc_worker_utils.py:226]   File "/home/ubuntu/miniforge3/envs/jinsu/lib/python3.10/site-packages/vllm/distributed/parallel_state.py", line 399, in broadcast_tensor_dict
(VllmWorkerProcess pid=3673853) ERROR 07-29 12:03:23 multiproc_worker_utils.py:226]     torch.distributed.broadcast_object_list(recv_metadata_list,
(VllmWorkerProcess pid=3673853) ERROR 07-29 12:03:23 multiproc_worker_utils.py:226]   File "/home/ubuntu/miniforge3/envs/jinsu/lib/python3.10/site-packages/torch/distributed/c10d_logger.py", line 75, in wrapper
(VllmWorkerProcess pid=3673853) ERROR 07-29 12:03:23 multiproc_worker_utils.py:226]     return func(*args, **kwargs)
(VllmWorkerProcess pid=3673853) ERROR 07-29 12:03:23 multiproc_worker_utils.py:226]   File "/home/ubuntu/miniforge3/envs/jinsu/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 2649, in broadcast_object_list
(VllmWorkerProcess pid=3673853) ERROR 07-29 12:03:23 multiproc_worker_utils.py:226]     broadcast(object_sizes_tensor, src=src, group=group)
(VllmWorkerProcess pid=3673853) ERROR 07-29 12:03:23 multiproc_worker_utils.py:226]   File "/home/ubuntu/miniforge3/envs/jinsu/lib/python3.10/site-packages/torch/distributed/c10d_logger.py", line 75, in wrapper
(VllmWorkerProcess pid=3673853) ERROR 07-29 12:03:23 multiproc_worker_utils.py:226]     return func(*args, **kwargs)
(VllmWorkerProcess pid=3673853) ERROR 07-29 12:03:23 multiproc_worker_utils.py:226]   File "/home/ubuntu/miniforge3/envs/jinsu/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 2144, in broadcast
(VllmWorkerProcess pid=3673853) ERROR 07-29 12:03:23 multiproc_worker_utils.py:226]     work.wait()
(VllmWorkerProcess pid=3673853) ERROR 07-29 12:03:23 multiproc_worker_utils.py:226] RuntimeError: [../third_party/gloo/gloo/transport/tcp/unbound_buffer.cc:81] Timed out waiting 1800000ms for recv operation to complete
(VllmWorkerProcess pid=3673853) ERROR 07-29 12:03:23 multiproc_worker_utils.py:226]
(VllmWorkerProcess pid=3673855) ERROR 07-29 12:03:24 multiproc_worker_utils.py:226] Exception in worker VllmWorkerProcess while processing method start_worker_execution_loop: [../third_party/gloo/gloo/transport/tcp/unbound_buffer.cc:81] Timed out waiting 1800000ms for recv operation to complete, Traceback (most recent call last):
(VllmWorkerProcess pid=3673855) ERROR 07-29 12:03:24 multiproc_worker_utils.py:226]   File "/home/ubuntu/miniforge3/envs/jinsu/lib/python3.10/site-packages/vllm/executor/multiproc_worker_utils.py", line 223, in _run_worker_process
(VllmWorkerProcess pid=3673855) ERROR 07-29 12:03:24 multiproc_worker_utils.py:226]     output = executor(*args, **kwargs)
(VllmWorkerProcess pid=3673855) ERROR 07-29 12:03:24 multiproc_worker_utils.py:226]   File "/home/ubuntu/miniforge3/envs/jinsu/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
(VllmWorkerProcess pid=3673855) ERROR 07-29 12:03:24 multiproc_worker_utils.py:226]     return func(*args, **kwargs)
(VllmWorkerProcess pid=3673855) ERROR 07-29 12:03:24 multiproc_worker_utils.py:226]   File "/home/ubuntu/miniforge3/envs/jinsu/lib/python3.10/site-packages/vllm/worker/worker.py", line 294, in start_worker_execution_loop
(VllmWorkerProcess pid=3673855) ERROR 07-29 12:03:24 multiproc_worker_utils.py:226]     while self._execute_model_non_driver():
(VllmWorkerProcess pid=3673855) ERROR 07-29 12:03:24 multiproc_worker_utils.py:226]   File "/home/ubuntu/miniforge3/envs/jinsu/lib/python3.10/site-packages/vllm/worker/worker.py", line 303, in _execute_model_non_driver
(VllmWorkerProcess pid=3673855) ERROR 07-29 12:03:24 multiproc_worker_utils.py:226]     data = broadcast_tensor_dict(src=0)
(VllmWorkerProcess pid=3673855) ERROR 07-29 12:03:24 multiproc_worker_utils.py:226]   File "/home/ubuntu/miniforge3/envs/jinsu/lib/python3.10/site-packages/vllm/distributed/communication_op.py", line 32, in broadcast_tensor_dict
(VllmWorkerProcess pid=3673855) ERROR 07-29 12:03:24 multiproc_worker_utils.py:226]     return get_tp_group().broadcast_tensor_dict(tensor_dict, src)
(VllmWorkerProcess pid=3673855) ERROR 07-29 12:03:24 multiproc_worker_utils.py:226]   File "/home/ubuntu/miniforge3/envs/jinsu/lib/python3.10/site-packages/vllm/distributed/parallel_state.py", line 399, in broadcast_tensor_dict
(VllmWorkerProcess pid=3673855) ERROR 07-29 12:03:24 multiproc_worker_utils.py:226]     torch.distributed.broadcast_object_list(recv_metadata_list,
(VllmWorkerProcess pid=3673855) ERROR 07-29 12:03:24 multiproc_worker_utils.py:226]   File "/home/ubuntu/miniforge3/envs/jinsu/lib/python3.10/site-packages/torch/distributed/c10d_logger.py", line 75, in wrapper
(VllmWorkerProcess pid=3673855) ERROR 07-29 12:03:24 multiproc_worker_utils.py:226]     return func(*args, **kwargs)
(VllmWorkerProcess pid=3673855) ERROR 07-29 12:03:24 multiproc_worker_utils.py:226]   File "/home/ubuntu/miniforge3/envs/jinsu/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 2649, in broadcast_object_list
(VllmWorkerProcess pid=3673855) ERROR 07-29 12:03:24 multiproc_worker_utils.py:226]     broadcast(object_sizes_tensor, src=src, group=group)
(VllmWorkerProcess pid=3673855) ERROR 07-29 12:03:24 multiproc_worker_utils.py:226]   File "/home/ubuntu/miniforge3/envs/jinsu/lib/python3.10/site-packages/torch/distributed/c10d_logger.py", line 75, in wrapper
(VllmWorkerProcess pid=3673855) ERROR 07-29 12:03:24 multiproc_worker_utils.py:226]     return func(*args, **kwargs)
(VllmWorkerProcess pid=3673855) ERROR 07-29 12:03:24 multiproc_worker_utils.py:226]   File "/home/ubuntu/miniforge3/envs/jinsu/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 2144, in broadcast
(VllmWorkerProcess pid=3673855) ERROR 07-29 12:03:24 multiproc_worker_utils.py:226]     work.wait()
(VllmWorkerProcess pid=3673855) ERROR 07-29 12:03:24 multiproc_worker_utils.py:226] RuntimeError: [../third_party/gloo/gloo/transport/tcp/unbound_buffer.cc:81] Timed out waiting 1800000ms for recv operation to complete
(VllmWorkerProcess pid=3673855) ERROR 07-29 12:03:24 multiproc_worker_utils.py:226]
(VllmWorkerProcess pid=3673856) ERROR 07-29 12:03:24 multiproc_worker_utils.py:226] Exception in worker VllmWorkerProcess while processing method start_worker_execution_loop: [../third_party/gloo/gloo/transport/tcp/unbound_buffer.cc:81] Timed out waiting 1800000ms for recv operation to complete, Traceback (most recent call last):
(VllmWorkerProcess pid=3673856) ERROR 07-29 12:03:24 multiproc_worker_utils.py:226]   File "/home/ubuntu/miniforge3/envs/jinsu/lib/python3.10/site-packages/vllm/executor/multiproc_worker_utils.py", line 223, in _run_worker_process
(VllmWorkerProcess pid=3673856) ERROR 07-29 12:03:24 multiproc_worker_utils.py:226]     output = executor(*args, **kwargs)
(VllmWorkerProcess pid=3673856) ERROR 07-29 12:03:24 multiproc_worker_utils.py:226]   File "/home/ubuntu/miniforge3/envs/jinsu/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
(VllmWorkerProcess pid=3673856) ERROR 07-29 12:03:24 multiproc_worker_utils.py:226]     return func(*args, **kwargs)
(VllmWorkerProcess pid=3673856) ERROR 07-29 12:03:24 multiproc_worker_utils.py:226]   File "/home/ubuntu/miniforge3/envs/jinsu/lib/python3.10/site-packages/vllm/worker/worker.py", line 294, in start_worker_execution_loop
(VllmWorkerProcess pid=3673856) ERROR 07-29 12:03:24 multiproc_worker_utils.py:226]     while self._execute_model_non_driver():
(VllmWorkerProcess pid=3673856) ERROR 07-29 12:03:24 multiproc_worker_utils.py:226]   File "/home/ubuntu/miniforge3/envs/jinsu/lib/python3.10/site-packages/vllm/worker/worker.py", line 303, in _execute_model_non_driver
(VllmWorkerProcess pid=3673856) ERROR 07-29 12:03:24 multiproc_worker_utils.py:226]     data = broadcast_tensor_dict(src=0)
(VllmWorkerProcess pid=3673856) ERROR 07-29 12:03:24 multiproc_worker_utils.py:226]   File "/home/ubuntu/miniforge3/envs/jinsu/lib/python3.10/site-packages/vllm/distributed/communication_op.py", line 32, in broadcast_tensor_dict
(VllmWorkerProcess pid=3673856) ERROR 07-29 12:03:24 multiproc_worker_utils.py:226]     return get_tp_group().broadcast_tensor_dict(tensor_dict, src)
(VllmWorkerProcess pid=3673856) ERROR 07-29 12:03:24 multiproc_worker_utils.py:226]   File "/home/ubuntu/miniforge3/envs/jinsu/lib/python3.10/site-packages/vllm/distributed/parallel_state.py", line 399, in broadcast_tensor_dict
(VllmWorkerProcess pid=3673856) ERROR 07-29 12:03:24 multiproc_worker_utils.py:226]     torch.distributed.broadcast_object_list(recv_metadata_list,
(VllmWorkerProcess pid=3673856) ERROR 07-29 12:03:24 multiproc_worker_utils.py:226]   File "/home/ubuntu/miniforge3/envs/jinsu/lib/python3.10/site-packages/torch/distributed/c10d_logger.py", line 75, in wrapper
(VllmWorkerProcess pid=3673856) ERROR 07-29 12:03:24 multiproc_worker_utils.py:226]     return func(*args, **kwargs)
(VllmWorkerProcess pid=3673856) ERROR 07-29 12:03:24 multiproc_worker_utils.py:226]   File "/home/ubuntu/miniforge3/envs/jinsu/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 2649, in broadcast_object_list
(VllmWorkerProcess pid=3673856) ERROR 07-29 12:03:24 multiproc_worker_utils.py:226]     broadcast(object_sizes_tensor, src=src, group=group)
(VllmWorkerProcess pid=3673856) ERROR 07-29 12:03:24 multiproc_worker_utils.py:226]   File "/home/ubuntu/miniforge3/envs/jinsu/lib/python3.10/site-packages/torch/distributed/c10d_logger.py", line 75, in wrapper
(VllmWorkerProcess pid=3673856) ERROR 07-29 12:03:24 multiproc_worker_utils.py:226]     return func(*args, **kwargs)

In [68]:
df

,instruction,option
0,[Conversation]\n화자1: 국민지원금 신청 일이 다가오네요\n화자2: 아...,[Option]\nA. 국민 지원금 신청 자격은 아주 까다로운 편이다.\nB. 국민...
1,[Conversation]\n화자1: 국민지원금 신청 일이 다가오네요\n화자2: 아...,[Option]\nA. 화자1은 국민 지원금 신청 자격 기준에 대해 토론할 것이다....
2,[Conversation]\n화자1: 국민지원금 신청 일이 다가오네요\n화자2: 아...,[Option]\nA. 화자1은 국민지원금을 신청할 수 있다.\nB. 화자2는 자녀...
3,[Conversation]\n화자1: 국민지원금 신청 일이 다가오네요\n화자2: 아...,[Option]\nA. 화자1은 국민 지원금의 사용처에 대한 불만을 표현한다.\nB...
4,[Conversation]\n화자1: 국민지원금 신청 일이 다가오네요\n화자2: 아...,[Option]\nA. 화자1은 국민 지원금 신청 자격이 지나치게 까다로운 것이 황...
...,...,...
1995,[Conversation]\n화자1: 기숙사 생활하신 경험이 있으신가요?\n화자2:...,[Option]\nA. 화자1은 룸메이트와 잘 지냈다고 언급했다.\nB. 화자1은 ...
1996,[Conversation]\n화자1: 기숙사 생활하신 경험이 있으신가요?\n화자2:...,[Option]\nA. 화자2는 룸메이트와의 갈등을 해결하기 위해 노력했다.\nB....
1997,[Conversation]\n화자1: 기숙사 생활하신 경험이 있으신가요?\n화자2:...,[Option]\nA. 화자1은 룸메이트와 싸운 적이 있다.\nB. 화자1은 룸메이...
1998,[Conversation]\n화자1: 기숙사 생활하신 경험이 있으신가요?\n화자2:...,[Option]\nA. 화자1은 단체 생활 경험이 나쁘지 않았다.\nB. 화자2는 ...
1999,[Conversation]\n화자1: 기숙사 생활하신 경험이 있으신가요?\n화자2:...,[Option]\nA. 화자1은 룸메이트와의 갈등을 겪은 화자2를 안타깝게 생각한다...

In [69]:
df.to_csv('test.csv',index=False)

In [70]:
import pandas as pd
df = pd.read_csv('test.csv')
df['option']

0       [Option]\nA. 국민 지원금 신청 자격은 아주 까다로운 편이다.\nB. 국민...
1       [Option]\nA. 화자1은 국민 지원금 신청 자격 기준에 대해 토론할 것이다....
2       [Option]\nA. 화자1은 국민지원금을 신청할 수 있다.\nB. 화자2는 자녀...
3       [Option]\nA. 화자1은 국민 지원금의 사용처에 대한 불만을 표현한다.\nB...
4       [Option]\nA. 화자1은 국민 지원금 신청 자격이 지나치게 까다로운 것이 황...
                              ...
1995    [Option]\nA. 화자1은 룸메이트와 잘 지냈다고 언급했다.\nB. 화자1은 ...
1996    [Option]\nA. 화자2는 룸메이트와의 갈등을 해결하기 위해 노력했다.\nB....
1997    [Option]\nA. 화자1은 룸메이트와 싸운 적이 있다.\nB. 화자1은 룸메이...
1998    [Option]\nA. 화자1은 단체 생활 경험이 나쁘지 않았다.\nB. 화자2는 ...
1999    [Option]\nA. 화자1은 룸메이트와의 갈등을 겪은 화자2를 안타깝게 생각한다...
Name: option, Length: 2000, dtype: object

In [26]:
json = pd.read_json('./일상대화-Data/일상대화요약_test.json')
json['output'] = df['output']
json

FileNotFoundError: File ./일상대화-Data/일상대화요약_test.json does not exist

In [ ]:
# DataFrame을 JSON 파일로 저장, orient='records'와 lines=True 옵션 사용
json.to_json('일상대화_full_template.json', force_ascii=False, orient='records', lines=True)